
spring:
  application:
    name: lancamentos
  datasource:
    url: jdbc:postgresql://localhost:5432/lancamento_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

