CREATE TABLE public.pessoas (
    id bigint generated by default as identity,
    nome varchar(255) NOT NULL,
    cpf varchar(255) NULL,
	data_nascimento date NULL,
	CONSTRAINT pessoas_cpf_key UNIQUE (cpf),
	CONSTRAINT pessoas_pkey PRIMARY KEY (id)
);