 CREATE TABLE public.contas (
    id bigint generated by default as identity,
    ativo boolean NOT NULL,
    limite_saque_diario numeric(10,2) NOT NULL,
    saldo numeric(10,2) NOT NULL,
    data_criacao timestamp(6) NULL,
    tipo_conta varchar(255) NULL,
    pessoa_id int NULL,
    CONSTRAINT contas_pkey PRIMARY KEY (id)
    );

    -- public.contas chaves estrangeiras

    ALTER TABLE public.contas ADD CONSTRAINT fkq8ertxsdb76ats2ullvqvnsmi FOREIGN KEY (pessoa_id) REFERENCES public.pessoas(id);