
CREATE TABLE public.users (
    id bigint generated by default as identity,
	enabled BOOLEAN NOT NULL DEFAULT TRUE,
	login varchar(255) NULL,
	"password" varchar(255) NULL,
	CONSTRAINT users_pkey PRIMARY KEY (id)
);